default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minhvo_demo_development

test:
  <<: *default
  database: minhvo_demo_test

production:
  <<: *default
  database: minhvo_demo_production
  username: ubuntu
  password: abc123
